// <auto-generated />
using Ch04MultiPageAmbroson.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ch04MultiPageAmbroson.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20210719205727_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ch04MultiPageAmbroson.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneId");

                    b.ToTable("PhoneContacts");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            Name = "Nick",
                            Notes = "Its me!",
                            Number = "515-555-1234"
                        },
                        new
                        {
                            PhoneId = 2,
                            Name = "Hayley",
                            Notes = "Wifey",
                            Number = "515-555-4321"
                        },
                        new
                        {
                            PhoneId = 3,
                            Name = "Griff",
                            Notes = "Big man Griffin",
                            Number = "515-555-1111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
