// <auto-generated />
using Ch04MultiPageAmbroson.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ch04MultiPageAmbroson.Migrations
{
    [DbContext(typeof(PhoneContext))]
    partial class PhoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ch04MultiPageAmbroson.Models.Contact", b =>
                {
                    b.Property<string>("ContactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = "M",
                            Name = "Mobile"
                        },
                        new
                        {
                            ContactId = "W",
                            Name = "Work"
                        },
                        new
                        {
                            ContactId = "H",
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("Ch04MultiPageAmbroson.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneId");

                    b.HasIndex("ContactId");

                    b.ToTable("PhoneContacts");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            ContactId = "M",
                            Name = "Nick",
                            Notes = "Its me!",
                            Number = "515-555-1234"
                        },
                        new
                        {
                            PhoneId = 2,
                            ContactId = "W",
                            Name = "Hayley",
                            Notes = "Wifey",
                            Number = "515-555-4321"
                        },
                        new
                        {
                            PhoneId = 3,
                            ContactId = "H",
                            Name = "Griff",
                            Notes = "Big man Griffin",
                            Number = "515-555-1111"
                        });
                });

            modelBuilder.Entity("Ch04MultiPageAmbroson.Models.Phone", b =>
                {
                    b.HasOne("Ch04MultiPageAmbroson.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
